# Generated by Django 3.1.2 on 2020-10-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
